# sonar.projectKey=Risheii_demo
# sonar.organization=risheii

# sonar.sources=.
# sonar.exclusions=node_modules/**

# sonar.sourceEncoding=UTF-8  

sonar.projectKey=day-1

sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_12647bd4a65faf9adf53ae35e09e5efa533593a3

sonar.exclusions=node_modules/**
    
sonar.sourceEncoding=UTF-8  