sonar.projectKey=Demo
sonar.sources=.

sonar.host.url=http://localhost:9000
sonar.login=sqp_9131d1dad409a32993bffaab62d4eefc59089acf

sonar.exclusions=node_modules/**,dist/**,coverage/**,.scannerwork/**